### PR TITLE
Fixes Deny x-frame-options Automattic/jetpack#21023

### LINKED ISSUE #21023: Detect X-Frame-Options DENY
Jetpack Boost uses iframes to generate Critical CSS. Some customers have run into an issue when they use the `X-Frame-Options: DENY` header to disallow their site loading inside an iframe.

Unfortunately, Jetpack Boost doesn't detect cases like these, and gives users a really unhelpful error message when this occurs: "It looks like this URL doesn't match: <URL>".

When loading content in an iframe fails, the Critical CSS generator library uses `diagnoseUrlError` (in browser-interface-iframe.js`) to load the same URL with `fetch` to diagnose what went wrong. That way, it can detect HTTP errors, redirects, etc - which aren't really detectable when an iframe load fails.

That method could be updated to check the response headers for `X-Frame-Options` deny, and throw an error which explains the sitaution.

Jetpack Boost's Critical CSS error handling code will also need to be updated to handle this error message, and show it in a user-friendly manner.

### PR DESCRIPTION
**Pull request by amustaque97**
### Changes Proposed in the PR

* In this commit I have updated `diagnoseUrlError` to handle
`x-frame-options: deny` configuration
* Created a new error class for better readability

### Screenshot
Screenshot from 2021-09-10 22-23-39

### Testing Instruction
* Replace line number 11 to `"jetpack-boost-critical-css-gen": "github:amustaque97/jetpack-boost-critical-css-gen#fix\/detect-xframe-options"` https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/package.json#L11
*  Navigate to jetpack repo/directory
* Build jetpack boost plugin `jetpack build`
* Open file `jetpack/tools/docker/wordpress/wp-config.php`
* At the end of the file add this line `header('X-Frame-Options: DENY');`
*  Run `jetpack docker up`
* Open local WordPress in browser
* Open jetpack boost and enable critical CSS
* Click on `See error message`

Fixes automattic/jetpack#21023

### CODE REVIEW

File: lib/errors.js [hunk 1]
```diff
@@ -126,6 +126,15 @@ class EmptyCSSError extends UrlError {
 	}
 }
 
+/**
+ * XFrameDenyError - Indicates that a requested URL failed due to x-frame-options deny configuration
+ */
+ class XFrameDenyError extends UrlError {
+	constructor( { url } ) {
+		super( 'XFrameDenyError', { url }, `Failed to process because of x-frame-options deny configration` );
```
Comment (thingalon) [inline lib/errors.js]:
```suggestion
		super( 'XFrameDenyError', { url }, `Failed to load ${ url } due to the "X-Frame-Options: DENY" header` );
```

**Review by thingalon — CHANGES_REQUESTED** [review]
Your implementation looks good. I've suggested an improvement to include the URL in the error message. I know it's not shown in Boost, but this library may get reused in other contexts, where the error text is the only useful output when something fails. :)

**Comment by amustaque97** [comment]
Hi @thingalon, I have addressed the review comments, please take a look at PR once again. I'm attaching a screenshot after making changes.
Screenshot 2021-09-13 21:41:21

**Review by thingalon — APPROVED** [review]
👍  Lovely! Thank you for contributing to the Critical CSS gen library :)
